spring.application.name=aiskin
# Server port (Render provides PORT env var)
server.port=${PORT:8080}

# MySQL Database
spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/glowai_db}
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:#sarangi1262}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Gemini API key
gemini.api.key=${GEMINI_API_KEY:AIzaSyCvpyAf7E-9SePlbTzl1GJGJA5hYJJTehs}
server.tomcat.max-http-form-post-size=15MB
spring.servlet.multipart.max-file-size=15MB
spring.servlet.multipart.max-request-size=15MB

